name: Publish release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Github Release
      uses: elgohr/Github-Release-Action@v3.1
      with:
        args: NewReleaseFromGithubActions
